#  .travis.yml 配置信息
# 配置语言
language: node_js
# 语言版本 stable
node_js: stable


# S: Build Lifecycle


before_install:
  - npm i -g hexo-cli
  - git clone https://github.com/iissnan/hexo-theme-next themes/next
  - cp conf/next/_next_config.yml themes/next/_config.yml
  - cp conf/next/custom.styl themes/next/source/css/_variables/custom.styl
# 安装依赖
install:
  - npm install

 # 部署命令
script:
  - hexo clean
  - hexo generate

# 提交内容及git 用户信息
# after_script:
#   - cd ./public
#   - git add .
#   - git commit -m ''
#   - git push --quiet --force https://$REPO_TOKEN@github.com/zsirfs/zsirfs.github.io.git master
# E: Build LifeCycle

before_deploy:
  # Set up git user name and tag this commit
  # - cd ./public
  # - git init
  # - git config --local user.name "zsirfs"
  # - git config --local user.email "zhenglfsir@gmail.com"

deploy:
  provider: pages
  email: zhenglfsir@gmail.com
  name: 'zsirfs'
  skip-cleanup: true
  local-dir: public
  keep-history: true
  github-token: $GITHUB_TOKEN
  target-branch: master
  project-name: zsirfs.github.io
  verbose: true
  on:
    all_branches: true

# 项目所在分支
branches:
  only:
    - src
cache:
  directories:
    - "node_modules"

# 项目git地址	
env:
 global:
