#  .travis.yml 配置信息
# 配置语言
language: node_js
# 语言版本 stable
node_js: stable


# S: Build Lifecycle


# 安装依赖
install:
  - npm install hexo-cli -g
  - npm install

 # 部署命令
script:
  - hexo clean
  - hexo generate --deploy

# 提交内容及git 用户信息
after_script:
# E: Build LifeCycle


# 项目所在分支
branches:
  only:
    - src

# 项目git地址	
env:
 global:
   - GH_REF: github.com/zsirfs/zsirfs.github.io.git
